# Site settings
title: Gurdeep Sira
twitter_username: rob_hinds
name: Gurdeep Sira

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/gurdeepsira
 - title: StackOverflow
   url: 
 - title: DZone
   url: https://www.linkedin.com/in/gurdip-sira-70384b5/
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Azure
 - AWS
 - TeamCity
 - Git/GitHub
 - Chef
 - Octopus Deploy
 - Azure DevOps
 - Powershell
 - C#
 - IIS
 - Kubernetes
 - DevOps Culture
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Senior IT Analyst
   start: 2o14
   end: Ongoing
   employer: Arup
   description: Currently hold partial responsibility for the Azure environment, comprising of Virtual Machines, App Services, functions, scheduler jobs, API management and more. I have worked on operationalising the Azure cloud environment for production usage across the form, thus working to keep cost down, and increase enterprise agility. I also administer and enforce security, using tools such as Keyvault, Security Center and RBAC for controlled access to Azure resources. The azure environment is administered using Terraform and Packer, alongside Azure DevOps to serve as a pipeline for automated releases. I have also implemented a DevOps pipeline for automated releases into the Azure environment, using Azure DevOps, Octopus Deploy and New Relic. This has led to quicker, more stable releases, and faster velocity and business agility. I am currently working on a large scale migration from all our On Premises datacentres to Azure and AWS in a multi cloud strategy, and using a mix of hosting and deployment models.
 - title: SharePoint Support Engineer
   start: 2013
   end: 2014
   employer: Content and Code
   description: Responsible for SharePoint support.

#Education is required
education:
 - level: Bachelors
   date: 2009
   subject: Business and Management (Computing)
   school: Brunel University

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/37e0c5068e547b5629351060286e2b16
   courses:
    - title: Moving to the cloud
      link: https://www.coursera.org/learn/cloud-computing-adoption/
      date: 2019
    - title: DevOps Culture and Mindset
      link: https://www.coursera.org/account/accomplishments/certificate/SQ2RWSRJSJYG
      date: 2019
    - title: Microservices Caching Fundamentals
      link: 
    - title: Automating architectural decisions through fitness functions
    - title: Shaping and Communicating Architectural Decisions
    - title: Getting Unstuck
   

#List of interesting Github repo/projects to include - optional
github:
 - gurdeepsira/gurdeepsira.github.io
#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/32484/gurdeeps
   flairimageurl: https://stackexchange.com/users/flair/15399.png

intro: |
  I am an engineer with 10 years experience working in technology. I have worked primarily as a web developer in ASP.NET and C#, and then SharePoint/Office 365. Along came Azure AD and Azure, and my journey started to learn Azure. AWS came next and DevOps was a good fit for me given my early dev background, and my understanding in Business Management principles such as Lean, which is where DevOps stems from. <br />
  This site and the accompanying GitHub repo has been built to showcase my skills and provide practical insight into my abilities and projects.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Powershell</strong>: My current role uses Powershell for the automation and administration of AWS/Azure cloud platforms.<br/><br/>
   <strong>Azure</strong>: I am experienced in administration of Azure services, as well as configuring Azure for adoption (subscription, accounts, etc). <br/><br/>
   <strong>AWS</strong> I have worked on AWS projects, where I have needed to configure various services as well udnertaking large scale migrations. <br/><br/>
   <strong>Terraform</strong>: I have moved towards a model for using Terraform for automated provisioning, and IaC principles. <br/>
